// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxMD12Xup9HGQ6xVYRjdZfg3Q0-xjreSo',
    appId: '1:932209267469:android:3079c6578134bd354c5644',
    messagingSenderId: '932209267469',
    projectId: 'epixrewards-6d16b',
    databaseURL: 'https://epixrewards-6d16b-default-rtdb.firebaseio.com',
    storageBucket: 'epixrewards-6d16b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQEFlF6kyv9cDg9pdt6gQSK-8VhmOv6GQ',
    appId: '1:932209267469:ios:3d5c101c4f1069d94c5644',
    messagingSenderId: '932209267469',
    projectId: 'epixrewards-6d16b',
    databaseURL: 'https://epixrewards-6d16b-default-rtdb.firebaseio.com',
    storageBucket: 'epixrewards-6d16b.appspot.com',
    androidClientId: '932209267469-k16bi52b56q6q5u4evkfumhrm3upoasa.apps.googleusercontent.com',
    iosClientId: '932209267469-d6nr1gd9sta9em3vc0vc6i1qt4l5uqom.apps.googleusercontent.com',
    iosBundleId: 'com.example.payWithFlutterWordpress',
  );
}
